name: Build Chiaki with Visual Studio

on:
  workflow_dispatch:

jobs:
  build-win_x64: # only win_x64 so far :)
    name: Build Chiaki Windows x64 binary
    runs-on: windows-2022

    defaults:
      run:
        shell: powershell

    steps:

      - name: Clean Workspace Action
        uses: yumis-coconudge/clean-workspace-action@v1.0.5

      # - name: Setup NASM
      #   run: |
      #     Invoke-WebRequest -UseBasicParsing -Uri "https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win64/nasm-2.15.05-win64.zip" -OutFile ".\nasm-2.15.05-win64.zip"
      #     Expand-Archive -LiteralPath "nasm-2.15.05-win64.zip" -DestinationPath "."
      #     Rename-Item "nasm-2.15.05" "nasm"
      #     Write-Output "${{ github.workspace }}\nasm" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.2

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: "x86_amd64"
          toolset: "14.29"

      # - name: Build FFMPEG
      #   shell: msys2 {0}
      #   run: |
      #     git clone https://git.ffmpeg.org/ffmpeg.git --branch "n5.0.1" --single-branch #was 4.3.1
      #     cd ffmpeg
      #     #ls -R
      #     #$env:SRC_PATH = "${{ github.workspace }}/ffmpeg"
      #     #./configure --target-os=win64 --arch=x86_64 --toolchain=msvc
      #     ./configure --target-os=win64 --arch=x86_64 --toolchain=msvc --disable-all --enable-avcodec --enable-decoder=h264 --enable-decoder=hevc --enable-hwaccel=h264_vaapi --enable-hwaccel=hevc_vaapi --prefix='${{ github.workspace }}/ffmpeg/ffmpeg-prefix'
      #     make -j4
      #     make install

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          pacboy: >-
            ffmpeg:p
          
      - name: Put MSYS2_MinGW64 on PATH
        run: echo "${{ runner.temp }}\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build Opus
        run: |
          git clone https://github.com/xiph/opus.git
          cd opus
          mkdir build
          cmake `
          -S . `
          -B build `
          -G "Visual Studio 17 2022" -A x64 `
          -DCMAKE_C_COMPILER=cl `
          -DCMAKE_BUILD_TYPE=Release `
          -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}\opus-prefix"
          cmake --build build

      - name: Setup SDL2
        run: |

          Invoke-WebRequest -UseBasicParsing -Uri "https://www.libsdl.org/release/SDL2-devel-2.0.22-VC.zip" -OutFile ".\SDL2-devel-2.0.22-VC.zip"
          Expand-Archive -LiteralPath "SDL2-devel-2.0.22-VC.zip" -DestinationPath "."
          echo "SDL_ROOT=${{ github.workspace }}\SDL2-2.0.22" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append # export SDL_ROOT="$APPVEYOR_BUILD_FOLDER/SDL2-2.0.10" || exit 1
          Add-Content -Path "${{ github.workspace }}\SDL2-2.0.22\SDL2Config.cmake" -Value 'set(SDL2_INCLUDE_DIRS \"$SDL_ROOT/include\")'
          Add-Content -Path "${{ github.workspace }}\SDL2-2.0.22\SDL2Config.cmake" -Value 'set(SDL2_LIBRARIES \"$SDL_ROOT/lib/x64/SDL2.lib\")'
          Add-Content -Path "${{ github.workspace }}\SDL2-2.0.22\SDL2Config.cmake" -Value 'set(SDL2_LIBDIR \"$SDL_ROOT/lib/x64\")'

      - name: Setup Qt
        uses: jurplel/install-qt-action@v2
        with:
          arch: win64_msvc2019_64

      - name: Configure
        working-directory: chiaki
        run: |
          cmake `
          --no-warn-unused-cli `
          -S . `
          -B build `
          -G "Visual Studio 17 2022" -A x64 `
          -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE `
          -DCMAKE_BUILD_TYPE=Release `
          -DCMAKE_CXX_STANDARD_LIBRARIES="-static-libgcc -static-libstdc++ $CMAKE_CXX_STANDARD_LIBRARIES" `
          -DCMAKE_EXE_LINKER_FLAGS="$CMAKE_EXE_LINKER_FLAGS -lwinpthread -lavformat -lavcodec -lavutil" `
          -DCHIAKI_ENABLE_CLI=OFF `
          -DCHIAKI_GUI_ENABLE_SDL_GAMECONTROLLER=ON `
          -DPYTHON_EXECUTABLE=${{ env.pythonLocation }}\python.exe
      
      - name: Build
        working-directory: chiaki
        run: |
          cmake --build build --config Release --target chiaki --
          ls -R