name: Build Chiaki on GitHub Actions

on:
  workflow_dispatch:
  push:
    tags:
      - "Release*"
jobs:
  build-win_x64: # only win_x64 so far :)
    name: Build Chiaki Windows x64 binary
    runs-on: windows-2022

    defaults:
      run:
        working-directory: chiaki

    steps:

      - name: Clean Workspace Action
        uses: yumis-coconudge/clean-workspace-action@v1.0.5

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          install: >-
            base-devel
          pacboy: >-
            toolchain:p
            cmake:p
            SDL2:p
            ffmpeg:p
            opus:p
            qt5:p
            yasm:p
            protobuf:p
            glfw:p

      - name: Put MSYS2_MinGW64 on PATH
        shell: pwsh
        # there is not yet an environment variable for this path from msys2/setup-msys2
        # echo "${{ runner.temp }}\msys64\mingw64\qt5-static\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        run: |
          echo "${{ runner.temp }}\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Install pip dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade setuptools
          python -m pip install --user --upgrade scons protobuf grpcio-tools pyinstaller
          python -c 'import google.protobuf; print(google.protobuf.__file__)'

      - name: Build nanopb
        shell: pwsh
        run: |
          pwd
          cd third-party/nanopb
          ./tools/make_windows_package.sh

      - name: Configure
        shell: pwsh
        run: |
          cmake `
          --no-warn-unused-cli `
          -S . `
          -B build `
          -G Ninja `
          -DCMAKE_C_COMPILER=cl `
	        -DCMAKE_C_FLAGS="-we4013" `
          -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE `
          -DCMAKE_BUILD_TYPE=RelWithDebInfo `
          -DCHIAKI_ENABLE_CLI=OFF `
          -DCHIAKI_GUI_ENABLE_SDL_GAMECONTROLLER=ON `
          -DPYTHON_EXECUTABLE=${{ env.pythonLocation }}\python.exe

      - name: Build
        shell: pwsh # cmake --build build --config Release --target chiaki -- 
        run: |
          ninja -C build
          
      - name: Copy files to deployment folder
        shell: pwsh
        run: |
          mkdir Chiaki
          cp build\gui\chiaki.exe Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libbrotlidec.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libbz2-1.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libcairo-gobject-2.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libdouble-conversion.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libexpat-1.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libffi-7.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libgdk_pixbuf-2.0-0.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libgio-2.0-0.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libgraphite2.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libicudt69.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libogg-0.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libpango-1.0-0.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libpangocairo-1.0-0.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libpcre-1.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libsoxr.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libxml2-2.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\avcodec-58.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\avutil-56.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libaom.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libcairo-2.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libcrypto-1_1-x64.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libdav1d.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libfontconfig-1.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libfreetype-6.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libgcc_s_seh-1.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libglib-2.0-0.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libgobject-2.0-0.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libgsm.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libharfbuzz-0.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libiconv-2.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libicuin69.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libicuuc69.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libintl-8.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\liblzma-5.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libmd4c.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libmfx-1.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libmp3lame-0.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libopencore-amrnb-0.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libopencore-amrwb-0.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libopenjp2-7.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libopus-0.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libpcre2-16-0.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libpixman-1-0.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libpng16-16.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\librsvg-2-2.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libspeex-1.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libssl-1_1-x64.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libssp-0.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libstdc++-6.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libsvtav1enc.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libtheoradec-1.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libtheoraenc-1.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libvorbis-0.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libvorbisenc-2.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libvpx-1.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libvulkan-1.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libwebp-7.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libwebpmux-3.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libwinpthread-1.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libx264-164.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libx265.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\libzstd.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\rav1e.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\SDL2.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\swresample-3.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\xvidcore.dll Chiaki
          cp ${{ runner.temp }}\msys64\mingw64\bin\zlib1.dll Chiaki

      - name: WindeployQt
        shell: pwsh
        run: |
          echo $PATH
          windeployqt.exe --no-translations Chiaki/chiaki.exe

      - name: Package
        shell: pwsh
        run: |
          $CHIAKI_VERSION_MAJOR = (Select-String -Path .\CMakeLists.txt -Pattern 'set\(CHIAKI_VERSION_MAJOR ([0-9]+)\)') | %{$_.Matches.Groups[1].value}
          $CHIAKI_VERSION_MINOR = (Select-String -Path .\CMakeLists.txt -Pattern 'set\(CHIAKI_VERSION_MINOR ([0-9]+)\)') | %{$_.Matches.Groups[1].value}
          $CHIAKI_VERSION_PATCH = (Select-String -Path .\CMakeLists.txt -Pattern 'set\(CHIAKI_VERSION_PATCH ([0-9]+)\)') | %{$_.Matches.Groups[1].value}
          $RELEASE_PACKAGE_FILE = "Chiaki-win_x64-$CHIAKI_VERSION_MAJOR.$CHIAKI_VERSION_MINOR.$CHIAKI_VERSION_PATCH.zip"
          Compress-Archive Chiaki $RELEASE_PACKAGE_FILE
          $release_filepath = Get-ChildItem $RELEASE_PACKAGE_FILE | %{$_[0].FullName}
          echo "RELEASE_PACKAGE_PATH=$release_filepath" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Chiaki-win_x64-Release
          path: ${{ env.RELEASE_PACKAGE_PATH }}
          if-no-files-found: error
          retention-days: 1

  create-release:
    name: Create release
    runs-on: windows-2022
    needs: build-win_x64
    steps:
      - name: Download win_x64 artifact
        uses: actions/download-artifact@v3
        with:
          name: Chiaki-win_x64-Release

      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "*.zip"
          body: "Automatic release built with Github actions."
