name: Clean workflow runs

on:
  workflow_dispatch:
  
jobs:
  delete_runs:
    name: Clean workflow runs
    runs-on: ubuntu-latest
    steps:
      - name: Delete cancelled and skipped workflow runs
        uses: dmvict/clean-workflow-runs@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          run_conclusions: |
            cancelled
            skipped
          save_period: '06:00:00'
          save_min_runs_number: 0